---

symbol: resnet_50_upsnet
gpus: '0'
# gpus: '0,1,2,3'
dataset:
  num_classes: 9
  num_seg_classes: 19
  dataset: Cityscapes
  dataset_path: "./data/cityscapes/"
  image_set: train
  root_path: "./data/"
  test_image_set: val

network:
  has_rpn: true
  has_rcnn: true
  has_mask_head: true
  has_fcn_head: true
  fcn_head: "FCNHead"
  fcn_num_layers: 2
  has_panoptic_head: true

test:
  scales:
  - 1024
  max_size: 2048
  batch_size: 1
  panoptic_stuff_area_limit: 2048
  vis_mask: false
